# Generated by Django 5.2.1 on 2025-06-15 23:30

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('gestao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areaprocesso',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nome_completo']},
        ),
        migrations.AlterModelOptions(
            name='historicalareaprocesso',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical area processo', 'verbose_name_plural': 'historical area processos'},
        ),
        migrations.AlterModelOptions(
            name='historicalcliente',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical cliente', 'verbose_name_plural': 'historical clientes'},
        ),
        migrations.AlterModelOptions(
            name='historicallancamentofinanceiro',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical lancamento financeiro', 'verbose_name_plural': 'historical lancamento financeiros'},
        ),
        migrations.AlterModelOptions(
            name='historicalmovimentacao',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical movimentacao', 'verbose_name_plural': 'historical movimentacaos'},
        ),
        migrations.AlterModelOptions(
            name='historicalmovimentacaoservico',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical movimentacao servico', 'verbose_name_plural': 'historical movimentacao servicos'},
        ),
        migrations.AlterModelOptions(
            name='historicalprocesso',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical processo', 'verbose_name_plural': 'historical processos'},
        ),
        migrations.AlterModelOptions(
            name='historicalservico',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical servico', 'verbose_name_plural': 'historical servicos'},
        ),
        migrations.AlterModelOptions(
            name='historicaltipoacao',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical tipo acao', 'verbose_name_plural': 'historical tipo acaos'},
        ),
        migrations.AlterModelOptions(
            name='historicaltipomovimentacao',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical tipo movimentacao', 'verbose_name_plural': 'historical tipo movimentacaos'},
        ),
        migrations.AlterModelOptions(
            name='historicaltiposervico',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical tipo servico', 'verbose_name_plural': 'historical tipo servicos'},
        ),
        migrations.AlterModelOptions(
            name='historicalusuarioperfil',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical usuario perfil', 'verbose_name_plural': 'historical usuario perfils'},
        ),
        migrations.AlterModelOptions(
            name='lancamentofinanceiro',
            options={},
        ),
        migrations.AlterModelOptions(
            name='movimentacao',
            options={},
        ),
        migrations.AlterModelOptions(
            name='movimentacaoservico',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pagamento',
            options={},
        ),
        migrations.AlterModelOptions(
            name='processo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='servico',
            options={'ordering': ['-data_inicio']},
        ),
        migrations.AlterModelOptions(
            name='tipoacao',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tipomovimentacao',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tiposervico',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usuarioperfil',
            options={},
        ),
        migrations.RemoveField(
            model_name='historicallancamentofinanceiro',
            name='origem',
        ),
        migrations.RemoveField(
            model_name='historicalmovimentacaoservico',
            name='tipo_movimentacao',
        ),
        migrations.RemoveField(
            model_name='historicalprocesso',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='historicalservico',
            name='dia_vencimento_mensal',
        ),
        migrations.RemoveField(
            model_name='historicalservico',
            name='valor_mensal',
        ),
        migrations.RemoveField(
            model_name='historicalusuarioperfil',
            name='oab_numero',
        ),
        migrations.RemoveField(
            model_name='historicalusuarioperfil',
            name='oab_uf',
        ),
        migrations.RemoveField(
            model_name='lancamentofinanceiro',
            name='origem',
        ),
        migrations.RemoveField(
            model_name='movimentacaoservico',
            name='tipo_movimentacao',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='dia_vencimento_mensal',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='valor_mensal',
        ),
        migrations.RemoveField(
            model_name='usuarioperfil',
            name='oab_numero',
        ),
        migrations.RemoveField(
            model_name='usuarioperfil',
            name='oab_uf',
        ),
        migrations.AlterField(
            model_name='contratohonorarios',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='contratohonorarios',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='historicalcontratohonorarios',
            name='content_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='historicalcontratohonorarios',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='historicalmovimentacao',
            name='data_prazo_final',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmovimentacao',
            name='data_publicacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmovimentacao',
            name='detalhes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmovimentacao',
            name='dias_prazo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmovimentacao',
            name='processo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestao.processo'),
        ),
        migrations.AlterField(
            model_name='historicalmovimentacao',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalmovimentacao',
            name='tipo_movimentacao',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestao.tipomovimentacao'),
        ),
        migrations.AlterField(
            model_name='historicalmovimentacao',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalmovimentacaoservico',
            name='data_atividade',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='historicalmovimentacaoservico',
            name='detalhes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmovimentacaoservico',
            name='servico',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestao.servico'),
        ),
        migrations.AlterField(
            model_name='historicalmovimentacaoservico',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalprocesso',
            name='advogado_responsavel',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalprocesso',
            name='cliente',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestao.cliente'),
        ),
        migrations.AlterField(
            model_name='historicalprocesso',
            name='descricao_caso',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalprocesso',
            name='numero_processo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalprocesso',
            name='observacoes_internas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalprocesso',
            name='status_processo',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('SUSPENSO', 'Suspenso'), ('ARQUIVADO', 'Arquivado')], default='ATIVO', max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalprocesso',
            name='tipo_acao',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestao.tipoacao'),
        ),
        migrations.AlterField(
            model_name='historicalprocesso',
            name='valor_causa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='historicalprocesso',
            name='vara_comarca_orgao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalservico',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='historicaltipoacao',
            name='area',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestao.areaprocesso'),
        ),
        migrations.AlterField(
            model_name='historicaltipoacao',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome do Tipo de Ação'),
        ),
        migrations.AlterField(
            model_name='historicalusuarioperfil',
            name='cargo',
            field=models.CharField(blank=True, choices=[('ADVOGADO', 'Advogado(a)'), ('ESTAGIARIO', 'Estagiário(a)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='data_prazo_final',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='data_publicacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='detalhes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='dias_prazo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='gestao.processo'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='tipo_movimentacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao.tipomovimentacao'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='movimentacaoservico',
            name='data_atividade',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='movimentacaoservico',
            name='detalhes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimentacaoservico',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='gestao.servico'),
        ),
        migrations.AlterField(
            model_name='movimentacaoservico',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='processo',
            name='advogado_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_responsaveis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='processo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='gestao.cliente'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='descricao_caso',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processo',
            name='numero_processo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='processo',
            name='observacoes_internas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processo',
            name='status_processo',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('SUSPENSO', 'Suspenso'), ('ARQUIVADO', 'Arquivado')], default='ATIVO', max_length=30),
        ),
        migrations.AlterField(
            model_name='processo',
            name='tipo_acao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos', to='gestao.tipoacao'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='valor_causa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='processo',
            name='vara_comarca_orgao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tipoacao',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_de_acao', to='gestao.areaprocesso'),
        ),
        migrations.AlterField(
            model_name='tipoacao',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome do Tipo de Ação'),
        ),
        migrations.AlterField(
            model_name='usuarioperfil',
            name='cargo',
            field=models.CharField(blank=True, choices=[('ADVOGADO', 'Advogado(a)'), ('ESTAGIARIO', 'Estagiário(a)')], max_length=20, null=True),
        ),
    ]
