# Generated by Django 5.2.1 on 2025-08-13 13:33

import django.db.models.deletion
import gestao.encoders
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculoParcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(default='Parcela Principal', max_length=255)),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Original')),
                ('data_evento', models.DateField(verbose_name='Data do Evento (para cálculo)')),
            ],
            options={
                'ordering': ['data_evento'],
            },
        ),
        migrations.CreateModel(
            name='CalculoFaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('indice', models.CharField(max_length=100, verbose_name='Índice de Correção')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('juros_tipo', models.CharField(choices=[('NENHUM', 'Nenhum'), ('SIMPLES', 'Simples'), ('COMPOSTO', 'Composto')], default='NENHUM', max_length=20)),
                ('juros_taxa_mensal', models.DecimalField(decimal_places=4, default=0.0, max_digits=8, verbose_name='Taxa de Juros Mensal (%)')),
                ('pro_rata', models.BooleanField(default=True, help_text='Calcular juros/correção proporcionais aos dias do mês.')),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faixas', to='gestao.calculoparcela')),
            ],
            options={
                'verbose_name': 'Faixa de Cálculo',
                'ordering': ['parcela', 'ordem', 'data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='CalculoRascunho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição do Cálculo')),
                ('data_transito_em_julgado', models.DateField(blank=True, null=True)),
                ('ultimo_resultado_json', models.JSONField(blank=True, encoder=gestao.encoders.DecimalEncoder, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_modificacao', models.DateTimeField(auto_now=True)),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rascunhos_calculo', to='gestao.processo')),
                ('usuario_criacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculos_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rascunho de Cálculo Judicial',
                'verbose_name_plural': 'Rascunhos de Cálculos Judiciais',
                'ordering': ['-data_modificacao'],
            },
        ),
        migrations.AddField(
            model_name='calculoparcela',
            name='rascunho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='gestao.calculorascunho'),
        ),
        migrations.CreateModel(
            name='CalculoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MULTA', 'Multa'), ('HONORARIO', 'Honorários'), ('CUSTAS', 'Custas')], max_length=20)),
                ('descricao', models.CharField(max_length=255)),
                ('base_incidencia', models.CharField(choices=[('PRINCIPAL_CORRIGIDO', 'Principal Corrigido'), ('PRINCIPAL_MAIS_JUROS', 'Principal + Juros'), ('VALOR_FIXO', 'Valor Fixo a Corrigir')], max_length=30)),
                ('percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('valor_fixo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('data_valor_fixo', models.DateField(blank=True, help_text='Data para iniciar a correção do valor fixo.', null=True)),
                ('rascunho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='gestao.calculorascunho')),
            ],
            options={
                'ordering': ['tipo'],
            },
        ),
    ]
