# Generated by Django 5.2.1 on 2025-06-16 13:49

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_historicalservico_responsavel_servico_responsavel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprocesso',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='cliente',
        ),
        migrations.CreateModel(
            name='ParteProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_participacao', models.CharField(choices=[('AUTOR', 'Polo Ativo (Autor)'), ('REU', 'Polo Passivo (Réu)'), ('TERCEIRO', 'Terceiro Interessado'), ('VITIMA', 'Vítima'), ('TESTEMUNHA', 'Testemunha')], max_length=20, verbose_name='Tipo de Participação')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='gestao.cliente')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partes', to='gestao.processo')),
                ('representado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representa', to='gestao.parteprocesso', verbose_name='É representado/assistido por')),
            ],
            options={
                'ordering': ['tipo_participacao', 'cliente__nome_completo'],
                'unique_together': {('processo', 'cliente')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalParteProcesso',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tipo_participacao', models.CharField(choices=[('AUTOR', 'Polo Ativo (Autor)'), ('REU', 'Polo Passivo (Réu)'), ('TERCEIRO', 'Terceiro Interessado'), ('VITIMA', 'Vítima'), ('TESTEMUNHA', 'Testemunha')], max_length=20, verbose_name='Tipo de Participação')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestao.cliente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestao.processo')),
                ('representado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestao.parteprocesso', verbose_name='É representado/assistido por')),
            ],
            options={
                'verbose_name': 'historical parte processo',
                'verbose_name_plural': 'historical parte processos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
