# Generated by Django 5.2.1 on 2025-06-18 14:21

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_remove_historicalprocesso_cliente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculoJudicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_calculo', models.DateTimeField(auto_now_add=True)),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_inicio_correcao', models.DateField()),
                ('data_fim_correcao', models.DateField()),
                ('indice_correcao', models.CharField(max_length=10)),
                ('juros_percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('multa_percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('honorarios_percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('valor_corrigido', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_final', models.DecimalField(decimal_places=2, max_digits=12)),
                ('memoria_calculo', models.JSONField()),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculos', to='gestao.processo')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCalculoJudicial',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('data_calculo', models.DateTimeField(blank=True, editable=False)),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_inicio_correcao', models.DateField()),
                ('data_fim_correcao', models.DateField()),
                ('indice_correcao', models.CharField(max_length=10)),
                ('juros_percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('multa_percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('honorarios_percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('valor_corrigido', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_final', models.DecimalField(decimal_places=2, max_digits=12)),
                ('memoria_calculo', models.JSONField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestao.processo')),
                ('responsavel', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical calculo judicial',
                'verbose_name_plural': 'historical calculo judicials',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
