# Generated by Django 5.2.1 on 2025-06-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0005_calculojudicial_historicalcalculojudicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculojudicial',
            name='correcao_pro_rata',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calculojudicial',
            name='juros_periodo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='calculojudicial',
            name='juros_tipo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='calculojudicial',
            name='multa_sobre_juros',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcalculojudicial',
            name='correcao_pro_rata',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcalculojudicial',
            name='juros_periodo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalcalculojudicial',
            name='juros_tipo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalcalculojudicial',
            name='multa_sobre_juros',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='calculojudicial',
            name='juros_percentual',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='calculojudicial',
            name='valor_corrigido',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='calculojudicial',
            name='valor_final',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='historicalcalculojudicial',
            name='juros_percentual',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcalculojudicial',
            name='valor_corrigido',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='historicalcalculojudicial',
            name='valor_final',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
