# Generated by Django 5.2.1 on 2025-06-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0006_calculojudicial_correcao_pro_rata_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculojudicial',
            options={'ordering': ['-data_calculo']},
        ),
        migrations.AddField(
            model_name='calculojudicial',
            name='descricao',
            field=models.CharField(default='Cálculo Padrão', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalcalculojudicial',
            name='descricao',
            field=models.CharField(default='Cálculo Padrão', max_length=255),
        ),
    ]
