# Generated by Django 5.2.1 on 2025-06-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0007_alter_calculojudicial_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculojudicial',
            name='juros_data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data Final dos Juros'),
        ),
        migrations.AddField(
            model_name='calculojudicial',
            name='juros_data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início dos Juros'),
        ),
        migrations.AddField(
            model_name='historicalcalculojudicial',
            name='juros_data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data Final dos Juros'),
        ),
        migrations.AddField(
            model_name='historicalcalculojudicial',
            name='juros_data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início dos Juros'),
        ),
    ]
