# Generated by Django 5.2.1 on 2025-06-19 23:39

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0008_calculojudicial_juros_data_fim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do Modelo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição / Instruções de Uso')),
                ('cabecalho', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Cabeçalho')),
                ('conteudo', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Corpo do Documento')),
                ('rodape', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Rodapé')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_modificacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modelo de Documento',
                'verbose_name_plural': 'Modelos de Documentos',
                'ordering': ['titulo'],
            },
        ),
    ]
