# Generated by Django 5.2.1 on 2025-06-22 15:45

import ckeditor_uploader.fields
import datetime
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0010_documento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['-data_criacao']},
        ),
        migrations.RemoveField(
            model_name='documento',
            name='data_modificacao',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='modelo_origem',
        ),
        migrations.RemoveField(
            model_name='historicalmovimentacao',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='historicalmovimentacao',
            name='dias_prazo',
        ),
        migrations.RemoveField(
            model_name='historicalparteprocesso',
            name='representado_por',
        ),
        migrations.RemoveField(
            model_name='movimentacao',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='movimentacao',
            name='dias_prazo',
        ),
        migrations.RemoveField(
            model_name='parteprocesso',
            name='representado_por',
        ),
        migrations.AddField(
            model_name='documento',
            name='arquivo_upload',
            field=models.FileField(blank=True, help_text='Anexe o arquivo original (PDF, DOCX, etc).', null=True, upload_to='processos/documentos/%Y/%m/', verbose_name='Arquivo'),
        ),
        migrations.AddField(
            model_name='documento',
            name='data_protocolo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora do Protocolo'),
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo_documento',
            field=models.CharField(choices=[('PETICAO', 'Petição'), ('OFICIO', 'Ofício'), ('CONTRATO', 'Contrato'), ('PROCURACAO', 'Procuração'), ('DECISAO', 'Decisão/Sentença'), ('PROVA', 'Prova'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20, verbose_name='Tipo do Documento'),
        ),
        migrations.AddField(
            model_name='historicalprocesso',
            name='bloqueios_penhoras',
            field=models.JSONField(blank=True, help_text="Estrutura flexível para registrar bloqueios. Ex: [{'sistema': 'SISBAJUD', 'valor': 1500.00}]", null=True, verbose_name='Bloqueios e Penhoras'),
        ),
        migrations.AddField(
            model_name='historicalprocesso',
            name='data_distribuicao',
            field=models.DateField(default=datetime.date.today, verbose_name='Data de Distribuição/Início'),
        ),
        migrations.AddField(
            model_name='historicalprocesso',
            name='data_transito_em_julgado',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Trânsito em Julgado'),
        ),
        migrations.AddField(
            model_name='historicalprocesso',
            name='execucao_iniciada',
            field=models.BooleanField(default=False, verbose_name='Execução Iniciada?'),
        ),
        migrations.AddField(
            model_name='historicalprocesso',
            name='fase',
            field=models.CharField(choices=[('POSTULATORIA', 'Postulatória'), ('INSTRUTORIA', 'Instrutória'), ('DECISORIA', 'Decisória'), ('RECURSAL', 'Recursal'), ('EXECUCAO', 'Execução'), ('ARQUIVAMENTO', 'Arquivamento')], default='POSTULATORIA', max_length=30, verbose_name='Fase Processual Atual'),
        ),
        migrations.AddField(
            model_name='historicalprocesso',
            name='grau_jurisdicao',
            field=models.CharField(choices=[('PRIMEIRO', '1º Grau'), ('SEGUNDO', '2º Grau'), ('SUPERIOR', 'Tribunal Superior')], default='PRIMEIRO', max_length=20, verbose_name='Grau de Jurisdição'),
        ),
        migrations.AddField(
            model_name='historicalprocesso',
            name='juiz_responsavel',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Juiz Responsável'),
        ),
        migrations.AddField(
            model_name='historicalprocesso',
            name='justica_gratuita',
            field=models.BooleanField(default=False, verbose_name='Justiça Gratuita'),
        ),
        migrations.AddField(
            model_name='historicalprocesso',
            name='link_acesso',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link do Processo Eletrônico'),
        ),
        migrations.AddField(
            model_name='historicalprocesso',
            name='nivel_permissao',
            field=models.CharField(choices=[('PUBLICO', 'Público para a Equipe'), ('RESTRITO', 'Restrito ao Responsável e Envolvidos')], default='PUBLICO', max_length=20, verbose_name='Nível de Permissão'),
        ),
        migrations.AddField(
            model_name='historicalprocesso',
            name='numero_outro_sistema',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº em Outro Sistema (PJe, etc.)'),
        ),
        migrations.AddField(
            model_name='historicalprocesso',
            name='numero_sei',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número SEI (se aplicável)'),
        ),
        migrations.AddField(
            model_name='historicalprocesso',
            name='prioridade_tramitacao',
            field=models.BooleanField(default=False, verbose_name='Prioridade na Tramitação'),
        ),
        migrations.AddField(
            model_name='historicalprocesso',
            name='resultado',
            field=models.CharField(blank=True, choices=[('PROCEDENTE', 'Procedente'), ('IMPROCEDENTE', 'Improcedente'), ('PARCIALMENTE', 'Parcialmente Procedente'), ('ACORDO', 'Acordo'), ('EXTINTO', 'Extinto sem mérito')], max_length=20, null=True, verbose_name='Resultado Final'),
        ),
        migrations.AddField(
            model_name='historicalprocesso',
            name='segredo_justica',
            field=models.BooleanField(default=False, verbose_name='Segredo de Justiça'),
        ),
        migrations.AddField(
            model_name='historicalprocesso',
            name='tribunal',
            field=models.CharField(blank=True, choices=[('TJSP', 'TJSP'), ('TJPR', 'TJPR'), ('TJRS', 'TJRS'), ('TRF1', 'TRF-1'), ('TRF2', 'TRF-2'), ('TRF3', 'TRF-3'), ('TRF4', 'TRF-4'), ('TRF5', 'TRF-5'), ('TRF6', 'TRF-6'), ('TST', 'TST'), ('STJ', 'STJ'), ('STF', 'STF'), ('OUTRO', 'Outro')], max_length=10, null=True, verbose_name='Tribunal'),
        ),
        migrations.AddField(
            model_name='historicalprocesso',
            name='valor_executado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Total Executado'),
        ),
        migrations.AddField(
            model_name='processo',
            name='advogados_envolvidos',
            field=models.ManyToManyField(blank=True, related_name='processos_envolvidos', to=settings.AUTH_USER_MODEL, verbose_name='Outros Colaboradores'),
        ),
        migrations.AddField(
            model_name='processo',
            name='bloqueios_penhoras',
            field=models.JSONField(blank=True, help_text="Estrutura flexível para registrar bloqueios. Ex: [{'sistema': 'SISBAJUD', 'valor': 1500.00}]", null=True, verbose_name='Bloqueios e Penhoras'),
        ),
        migrations.AddField(
            model_name='processo',
            name='data_distribuicao',
            field=models.DateField(default=datetime.date.today, verbose_name='Data de Distribuição/Início'),
        ),
        migrations.AddField(
            model_name='processo',
            name='data_transito_em_julgado',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Trânsito em Julgado'),
        ),
        migrations.AddField(
            model_name='processo',
            name='execucao_iniciada',
            field=models.BooleanField(default=False, verbose_name='Execução Iniciada?'),
        ),
        migrations.AddField(
            model_name='processo',
            name='fase',
            field=models.CharField(choices=[('POSTULATORIA', 'Postulatória'), ('INSTRUTORIA', 'Instrutória'), ('DECISORIA', 'Decisória'), ('RECURSAL', 'Recursal'), ('EXECUCAO', 'Execução'), ('ARQUIVAMENTO', 'Arquivamento')], default='POSTULATORIA', max_length=30, verbose_name='Fase Processual Atual'),
        ),
        migrations.AddField(
            model_name='processo',
            name='grau_jurisdicao',
            field=models.CharField(choices=[('PRIMEIRO', '1º Grau'), ('SEGUNDO', '2º Grau'), ('SUPERIOR', 'Tribunal Superior')], default='PRIMEIRO', max_length=20, verbose_name='Grau de Jurisdição'),
        ),
        migrations.AddField(
            model_name='processo',
            name='juiz_responsavel',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Juiz Responsável'),
        ),
        migrations.AddField(
            model_name='processo',
            name='justica_gratuita',
            field=models.BooleanField(default=False, verbose_name='Justiça Gratuita'),
        ),
        migrations.AddField(
            model_name='processo',
            name='link_acesso',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link do Processo Eletrônico'),
        ),
        migrations.AddField(
            model_name='processo',
            name='nivel_permissao',
            field=models.CharField(choices=[('PUBLICO', 'Público para a Equipe'), ('RESTRITO', 'Restrito ao Responsável e Envolvidos')], default='PUBLICO', max_length=20, verbose_name='Nível de Permissão'),
        ),
        migrations.AddField(
            model_name='processo',
            name='numero_outro_sistema',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº em Outro Sistema (PJe, etc.)'),
        ),
        migrations.AddField(
            model_name='processo',
            name='numero_sei',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número SEI (se aplicável)'),
        ),
        migrations.AddField(
            model_name='processo',
            name='prioridade_tramitacao',
            field=models.BooleanField(default=False, verbose_name='Prioridade na Tramitação'),
        ),
        migrations.AddField(
            model_name='processo',
            name='resultado',
            field=models.CharField(blank=True, choices=[('PROCEDENTE', 'Procedente'), ('IMPROCEDENTE', 'Improcedente'), ('PARCIALMENTE', 'Parcialmente Procedente'), ('ACORDO', 'Acordo'), ('EXTINTO', 'Extinto sem mérito')], max_length=20, null=True, verbose_name='Resultado Final'),
        ),
        migrations.AddField(
            model_name='processo',
            name='segredo_justica',
            field=models.BooleanField(default=False, verbose_name='Segredo de Justiça'),
        ),
        migrations.AddField(
            model_name='processo',
            name='tribunal',
            field=models.CharField(blank=True, choices=[('TJSP', 'TJSP'), ('TJPR', 'TJPR'), ('TJRS', 'TJRS'), ('TRF1', 'TRF-1'), ('TRF2', 'TRF-2'), ('TRF3', 'TRF-3'), ('TRF4', 'TRF-4'), ('TRF5', 'TRF-5'), ('TRF6', 'TRF-6'), ('TST', 'TST'), ('STJ', 'STJ'), ('STF', 'STF'), ('OUTRO', 'Outro')], max_length=10, null=True, verbose_name='Tribunal'),
        ),
        migrations.AddField(
            model_name='processo',
            name='valor_executado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Total Executado'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='conteudo',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Use para gerar petições no sistema. Para documentos externos, use o campo de upload.', null=True, verbose_name='Conteúdo Editável'),
        ),
        migrations.AlterField(
            model_name='historicalmovimentacao',
            name='data_prazo_final',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Prazo/Audiência'),
        ),
        migrations.AlterField(
            model_name='historicalmovimentacao',
            name='data_publicacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Ato/Publicação'),
        ),
        migrations.AlterField(
            model_name='historicalparteprocesso',
            name='tipo_participacao',
            field=models.CharField(choices=[('AUTOR', 'Polo Ativo'), ('REU', 'Polo Passivo'), ('TERCEIRO', 'Terceiro Interessado'), ('VITIMA', 'Vítima'), ('TESTEMUNHA', 'Testemunha')], max_length=20, verbose_name='Tipo de Participação'),
        ),
        migrations.AlterField(
            model_name='historicalprocesso',
            name='advogado_responsavel',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável'),
        ),
        migrations.AlterField(
            model_name='historicalprocesso',
            name='descricao_caso',
            field=models.TextField(blank=True, null=True, verbose_name='Assunto Principal / Descrição do Caso'),
        ),
        migrations.AlterField(
            model_name='historicalprocesso',
            name='numero_processo',
            field=models.CharField(blank=True, help_text='Formato: 0000000-00.0000.0.00.0000', max_length=25, null=True, verbose_name='Número do Processo (CNJ)'),
        ),
        migrations.AlterField(
            model_name='historicalprocesso',
            name='observacoes_internas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas Internas (visível apenas para a equipe)'),
        ),
        migrations.AlterField(
            model_name='historicalprocesso',
            name='status_processo',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('SUSPENSO', 'Suspenso'), ('ARQUIVADO', 'Arquivado'), ('EXTINTO', 'Extinto'), ('EM_RECURSO', 'Em Recurso'), ('ENCERRADO', 'Encerrado com Resolução')], default='ATIVO', max_length=30, verbose_name='Situação do Processo'),
        ),
        migrations.AlterField(
            model_name='historicalprocesso',
            name='tipo_acao',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestao.tipoacao', verbose_name='Classe Processual'),
        ),
        migrations.AlterField(
            model_name='historicalprocesso',
            name='valor_causa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor da Causa'),
        ),
        migrations.AlterField(
            model_name='historicalprocesso',
            name='vara_comarca_orgao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Órgão Julgador (Vara/Comarca)'),
        ),
        migrations.AlterField(
            model_name='historicaltipoacao',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome do Tipo de Ação/Classe Processual'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='data_prazo_final',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Prazo/Audiência'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='data_publicacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Ato/Publicação'),
        ),
        migrations.AlterField(
            model_name='parteprocesso',
            name='tipo_participacao',
            field=models.CharField(choices=[('AUTOR', 'Polo Ativo'), ('REU', 'Polo Passivo'), ('TERCEIRO', 'Terceiro Interessado'), ('VITIMA', 'Vítima'), ('TESTEMUNHA', 'Testemunha')], max_length=20, verbose_name='Tipo de Participação'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='advogado_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_responsaveis', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='descricao_caso',
            field=models.TextField(blank=True, null=True, verbose_name='Assunto Principal / Descrição do Caso'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='numero_processo',
            field=models.CharField(blank=True, help_text='Formato: 0000000-00.0000.0.00.0000', max_length=25, null=True, verbose_name='Número do Processo (CNJ)'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='observacoes_internas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas Internas (visível apenas para a equipe)'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='status_processo',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('SUSPENSO', 'Suspenso'), ('ARQUIVADO', 'Arquivado'), ('EXTINTO', 'Extinto'), ('EM_RECURSO', 'Em Recurso'), ('ENCERRADO', 'Encerrado com Resolução')], default='ATIVO', max_length=30, verbose_name='Situação do Processo'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='tipo_acao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos', to='gestao.tipoacao', verbose_name='Classe Processual'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='valor_causa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor da Causa'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='vara_comarca_orgao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Órgão Julgador (Vara/Comarca)'),
        ),
        migrations.AlterField(
            model_name='tipoacao',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome do Tipo de Ação/Classe Processual'),
        ),
        migrations.CreateModel(
            name='HistoricalDocumento',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do Documento')),
                ('tipo_documento', models.CharField(choices=[('PETICAO', 'Petição'), ('OFICIO', 'Ofício'), ('CONTRATO', 'Contrato'), ('PROCURACAO', 'Procuração'), ('DECISAO', 'Decisão/Sentença'), ('PROVA', 'Prova'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20, verbose_name='Tipo do Documento')),
                ('arquivo_upload', models.TextField(blank=True, help_text='Anexe o arquivo original (PDF, DOCX, etc).', max_length=100, null=True, verbose_name='Arquivo')),
                ('data_protocolo', models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora do Protocolo')),
                ('conteudo', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Use para gerar petições no sistema. Para documentos externos, use o campo de upload.', null=True, verbose_name='Conteúdo Editável')),
                ('data_criacao', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestao.processo')),
            ],
            options={
                'verbose_name': 'historical documento',
                'verbose_name_plural': 'historical documentos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalIncidente',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo de Incidente')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('RESOLVIDO', 'Resolvido'), ('PENDENTE', 'Pendente')], default='ABERTO', max_length=20, verbose_name='Status')),
                ('data_ocorrido', models.DateField(default=datetime.date.today, verbose_name='Data')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestao.processo')),
            ],
            options={
                'verbose_name': 'historical incidente',
                'verbose_name_plural': 'historical incidentes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRecurso',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('APELACAO', 'Apelação'), ('AGRAVO', 'Agravo de Instrumento'), ('ESPECIAL', 'Recurso Especial'), ('EXTRAORDINARIO', 'Recurso Extraordinário'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Tipo de Recurso')),
                ('data_interposicao', models.DateField(verbose_name='Data de Interposição')),
                ('resultado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Resultado')),
                ('detalhes', models.TextField(blank=True, null=True, verbose_name='Detalhes')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestao.processo')),
            ],
            options={
                'verbose_name': 'historical recurso',
                'verbose_name_plural': 'historical recursos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo de Incidente')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('RESOLVIDO', 'Resolvido'), ('PENDENTE', 'Pendente')], default='ABERTO', max_length=20, verbose_name='Status')),
                ('data_ocorrido', models.DateField(default=datetime.date.today, verbose_name='Data')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidentes', to='gestao.processo')),
            ],
            options={
                'ordering': ['-data_ocorrido'],
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('APELACAO', 'Apelação'), ('AGRAVO', 'Agravo de Instrumento'), ('ESPECIAL', 'Recurso Especial'), ('EXTRAORDINARIO', 'Recurso Extraordinário'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Tipo de Recurso')),
                ('data_interposicao', models.DateField(verbose_name='Data de Interposição')),
                ('resultado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Resultado')),
                ('detalhes', models.TextField(blank=True, null=True, verbose_name='Detalhes')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='gestao.processo')),
            ],
            options={
                'ordering': ['-data_interposicao'],
            },
        ),
    ]
