# Generated by Django 5.2.1 on 2025-06-22 16:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0011_alter_documento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='modelo_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao.modelodocumento', verbose_name='Gerado a partir do Modelo'),
        ),
        migrations.AddField(
            model_name='historicaldocumento',
            name='data_modificacao',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldocumento',
            name='modelo_origem',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestao.modelodocumento', verbose_name='Gerado a partir do Modelo'),
        ),
        migrations.AddField(
            model_name='historicalmovimentacao',
            name='data_criacao',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalmovimentacao',
            name='dias_prazo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Dias de Prazo'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='dias_prazo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Dias de Prazo'),
        ),
        migrations.AlterField(
            model_name='historicalprocesso',
            name='bloqueios_penhoras',
            field=models.JSONField(blank=True, help_text="Estrutura para registrar bloqueios. Ex: [{'sistema': 'SISBAJUD', 'valor': 1500.00}]", null=True, verbose_name='Bloqueios e Penhoras'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='bloqueios_penhoras',
            field=models.JSONField(blank=True, help_text="Estrutura para registrar bloqueios. Ex: [{'sistema': 'SISBAJUD', 'valor': 1500.00}]", null=True, verbose_name='Bloqueios e Penhoras'),
        ),
    ]
