# Generated by Django 5.2.1 on 2025-06-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0012_documento_data_modificacao_documento_modelo_origem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True, db_index=True, null=True, verbose_name='Data de Cadastro'),
        ),
        migrations.AddField(
            model_name='historicalcliente',
            name='data_cadastro',
            field=models.DateField(blank=True, db_index=True, editable=False, null=True, verbose_name='Data de Cadastro'),
        ),
    ]
