# Generated by Django 5.2.1 on 2025-06-26 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0015_popular_tipos_movimentacao'),
    ]

    operations = [
    ]
