# Generated by Django 5.2.1 on 2025-06-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0017_popular_tipos_movimentacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipomovimentacao',
            options={'ordering': ['nome']},
        ),
        migrations.AddField(
            model_name='historicalmovimentacao',
            name='hora_prazo',
            field=models.TimeField(blank=True, help_text='Preencha apenas para audiências ou eventos com hora marcada.', null=True, verbose_name='Horário'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='hora_prazo',
            field=models.TimeField(blank=True, help_text='Preencha apenas para audiências ou eventos com hora marcada.', null=True, verbose_name='Horário'),
        ),
    ]
