# Generated by Django 5.2.1 on 2025-06-26 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0018_alter_tipomovimentacao_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalparteprocesso',
            name='representado_por',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestao.parteprocesso'),
        ),
        migrations.AddField(
            model_name='parteprocesso',
            name='representado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representantes', to='gestao.parteprocesso'),
        ),
    ]
