# Generated by Django 5.2.1 on 2025-06-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0020_escritorioconfiguracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalusuarioperfil',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='historicalusuarioperfil',
            name='data_admissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Admissão'),
        ),
        migrations.AddField(
            model_name='historicalusuarioperfil',
            name='foto',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Foto de Perfil'),
        ),
        migrations.AddField(
            model_name='historicalusuarioperfil',
            name='oab',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nº da OAB (ex: 12345/PR)'),
        ),
        migrations.AddField(
            model_name='historicalusuarioperfil',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='usuarioperfil',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='usuarioperfil',
            name='data_admissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Admissão'),
        ),
        migrations.AddField(
            model_name='usuarioperfil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/', verbose_name='Foto de Perfil'),
        ),
        migrations.AddField(
            model_name='usuarioperfil',
            name='oab',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nº da OAB (ex: 12345/PR)'),
        ),
        migrations.AddField(
            model_name='usuarioperfil',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
    ]
