# Generated by Django 5.2.1 on 2025-07-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0021_historicalusuarioperfil_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmovimentacao',
            name='link_referencia',
            field=models.URLField(blank=True, help_text='Cole aqui o link para o andamento no sistema do tribunal, se houver.', max_length=500, null=True, verbose_name='Link de Referência'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='link_referencia',
            field=models.URLField(blank=True, help_text='Cole aqui o link para o andamento no sistema do tribunal, se houver.', max_length=500, null=True, verbose_name='Link de Referência'),
        ),
    ]
