# Generated by Django 5.2.1 on 2025-07-02 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0022_historicalmovimentacao_link_referencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escritorioconfiguracao',
            name='inscricao_municipal',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Municipal'),
        ),
        migrations.AddField(
            model_name='historicalservico',
            name='codigo_servico_municipal',
            field=models.CharField(blank=True, help_text='Ex: 01.07, 14.01, etc.', max_length=10, null=True, verbose_name='Cód. do Serviço Municipal (LC 116/03)'),
        ),
        migrations.AddField(
            model_name='servico',
            name='codigo_servico_municipal',
            field=models.CharField(blank=True, help_text='Ex: 01.07, 14.01, etc.', max_length=10, null=True, verbose_name='Cód. do Serviço Municipal (LC 116/03)'),
        ),
        migrations.CreateModel(
            name='NotaFiscalServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PROCESSANDO', 'Em Processamento'), ('ACEITO', 'Aceito'), ('ERRO', 'Erro'), ('CANCELADO', 'Cancelado')], default='PROCESSANDO', max_length=20)),
                ('numero_nfse', models.CharField(blank=True, max_length=15, null=True, verbose_name='Número da NFS-e')),
                ('codigo_verificacao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de Verificação')),
                ('data_emissao_nfse', models.DateTimeField(blank=True, null=True, verbose_name='Data de Emissão')),
                ('xml_enviado', models.TextField(blank=True, null=True)),
                ('xml_recebido', models.TextField(blank=True, null=True)),
                ('mensagem_retorno', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_fiscais', to='gestao.servico')),
            ],
            options={
                'verbose_name': 'Nota Fiscal de Serviço',
                'verbose_name_plural': 'Notas Fiscais de Serviço',
            },
        ),
    ]
