# Generated by Django 5.2.1 on 2025-07-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0023_escritorioconfiguracao_inscricao_municipal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallancamentofinanceiro',
            name='categoria',
            field=models.CharField(blank=True, choices=[('HONORARIOS', 'Honorários'), ('TAXAS', 'Taxas Judiciais/Administrativas'), ('CUSTAS', 'Custas Processuais'), ('ALUGUEL', 'Aluguel'), ('SALARIO', 'Salário'), ('OUTROS', 'Outros')], default='OUTROS', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='categoria',
            field=models.CharField(blank=True, choices=[('HONORARIOS', 'Honorários'), ('TAXAS', 'Taxas Judiciais/Administrativas'), ('CUSTAS', 'Custas Processuais'), ('ALUGUEL', 'Aluguel'), ('SALARIO', 'Salário'), ('OUTROS', 'Outros')], default='OUTROS', max_length=50, null=True),
        ),
    ]
