# Generated by Django 5.2.1 on 2025-07-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0024_historicallancamentofinanceiro_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='is_cliente',
            field=models.BooleanField(default=True, verbose_name='É um cliente?'),
        ),
        migrations.AddField(
            model_name='historicalcliente',
            name='is_cliente',
            field=models.BooleanField(default=True, verbose_name='É um cliente?'),
        ),
        migrations.AddField(
            model_name='historicalparteprocesso',
            name='is_cliente_do_processo',
            field=models.BooleanField(default=False, help_text='Marque esta opção se esta parte for o cliente do escritório neste processo específico.', verbose_name='É o cliente que representamos neste processo?'),
        ),
        migrations.AddField(
            model_name='parteprocesso',
            name='is_cliente_do_processo',
            field=models.BooleanField(default=False, help_text='Marque esta opção se esta parte for o cliente do escritório neste processo específico.', verbose_name='É o cliente que representamos neste processo?'),
        ),
    ]
