# Generated by Django 5.2.1 on 2025-07-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0025_cliente_is_cliente_historicalcliente_is_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escritorioconfiguracao',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
