# Generated by Django 5.2.1 on 2025-07-23 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0026_escritorioconfiguracao_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipomovimentacao',
            options={'ordering': ['-favorito', 'nome']},
        ),
        migrations.AddField(
            model_name='historicalmovimentacao',
            name='data_inicio_prazo',
            field=models.DateField(blank=True, null=True, verbose_name='Primeiro Dia do Prazo'),
        ),
        migrations.AddField(
            model_name='historicalmovimentacao',
            name='data_intimacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Intimação'),
        ),
        migrations.AddField(
            model_name='historicaltipomovimentacao',
            name='dias_antecedencia_lembrete',
            field=models.PositiveIntegerField(blank=True, help_text='Ex: 3. O sistema poderá usar este valor para criar um lembrete 3 dias antes do prazo final.', null=True, verbose_name='Antecedência para Lembrete (dias)'),
        ),
        migrations.AddField(
            model_name='historicaltipomovimentacao',
            name='fase_processual_sugerida',
            field=models.CharField(blank=True, choices=[('POSTULATORIA', 'Postulatória'), ('INSTRUTORIA', 'Instrutória'), ('DECISORIA', 'Decisória'), ('RECURSAL', 'Recursal'), ('EXECUCAO', 'Execução'), ('ARQUIVAMENTO', 'Arquivamento')], help_text='Associe este tipo de movimentação a uma fase do processo para facilitar a seleção.', max_length=30, null=True, verbose_name='Fase Processual Padrão'),
        ),
        migrations.AddField(
            model_name='historicaltipomovimentacao',
            name='favorito',
            field=models.BooleanField(default=False, help_text='Marque para que este tipo apareça no topo das listas de seleção.', verbose_name='Favorito'),
        ),
        migrations.AddField(
            model_name='historicaltipomovimentacao',
            name='tipo_contagem_prazo',
            field=models.CharField(choices=[('UTEIS', 'Dias Úteis'), ('CORRIDOS', 'Dias Corridos')], default='UTEIS', help_text='Define se o prazo deve ser contado em dias úteis ou corridos.', max_length=10, verbose_name='Tipo de Contagem do Prazo'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='data_inicio_prazo',
            field=models.DateField(blank=True, null=True, verbose_name='Primeiro Dia do Prazo'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='data_intimacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Intimação'),
        ),
        migrations.AddField(
            model_name='tipomovimentacao',
            name='dias_antecedencia_lembrete',
            field=models.PositiveIntegerField(blank=True, help_text='Ex: 3. O sistema poderá usar este valor para criar um lembrete 3 dias antes do prazo final.', null=True, verbose_name='Antecedência para Lembrete (dias)'),
        ),
        migrations.AddField(
            model_name='tipomovimentacao',
            name='fase_processual_sugerida',
            field=models.CharField(blank=True, choices=[('POSTULATORIA', 'Postulatória'), ('INSTRUTORIA', 'Instrutória'), ('DECISORIA', 'Decisória'), ('RECURSAL', 'Recursal'), ('EXECUCAO', 'Execução'), ('ARQUIVAMENTO', 'Arquivamento')], help_text='Associe este tipo de movimentação a uma fase do processo para facilitar a seleção.', max_length=30, null=True, verbose_name='Fase Processual Padrão'),
        ),
        migrations.AddField(
            model_name='tipomovimentacao',
            name='favorito',
            field=models.BooleanField(default=False, help_text='Marque para que este tipo apareça no topo das listas de seleção.', verbose_name='Favorito'),
        ),
        migrations.AddField(
            model_name='tipomovimentacao',
            name='tipo_contagem_prazo',
            field=models.CharField(choices=[('UTEIS', 'Dias Úteis'), ('CORRIDOS', 'Dias Corridos')], default='UTEIS', help_text='Define se o prazo deve ser contado em dias úteis ou corridos.', max_length=10, verbose_name='Tipo de Contagem do Prazo'),
        ),
        migrations.AlterField(
            model_name='historicalmovimentacao',
            name='data_prazo_final',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Prazo Final'),
        ),
        migrations.AlterField(
            model_name='historicalmovimentacao',
            name='data_publicacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Publicação'),
        ),
        migrations.AlterField(
            model_name='historicalmovimentacao',
            name='dias_prazo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Dias de Prazo (manual)'),
        ),
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='gestao.cliente'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='data_prazo_final',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Prazo Final'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='data_publicacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Publicação'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='dias_prazo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Dias de Prazo (manual)'),
        ),
        migrations.AlterField(
            model_name='movimentacaoservico',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes_servico', to='gestao.servico'),
        ),
    ]
