# Generated by Django 5.2.1 on 2025-07-28 13:20

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0027_alter_tipomovimentacao_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculojudicial',
            options={'verbose_name': 'Cálculo Judicial', 'verbose_name_plural': 'Cálculos Judiciais'},
        ),
        migrations.RemoveField(
            model_name='calculojudicial',
            name='data_fim_correcao',
        ),
        migrations.RemoveField(
            model_name='calculojudicial',
            name='data_inicio_correcao',
        ),
        migrations.RemoveField(
            model_name='calculojudicial',
            name='indice_correcao',
        ),
        migrations.RemoveField(
            model_name='calculojudicial',
            name='juros_percentual',
        ),
        migrations.AddField(
            model_name='calculojudicial',
            name='data_fim',
            field=models.DateField(default=datetime.date(2025, 7, 28)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculojudicial',
            name='data_inicio',
            field=models.DateField(default=datetime.date(2025, 7, 28)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculojudicial',
            name='gerar_memorial',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='calculojudicial',
            name='indice',
            field=models.CharField(default=datetime.date(2025, 7, 28), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculojudicial',
            name='juros_taxa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='calculojudicial',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='calculojudicial',
            name='honorarios_percentual',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='calculojudicial',
            name='juros_data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calculojudicial',
            name='juros_data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calculojudicial',
            name='juros_periodo',
            field=models.CharField(default='MENSAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='calculojudicial',
            name='juros_tipo',
            field=models.CharField(default='SIMPLES', max_length=20),
        ),
        migrations.AlterField(
            model_name='calculojudicial',
            name='memoria_calculo',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calculojudicial',
            name='multa_percentual',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='calculojudicial',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calculojudicial',
            name='valor_corrigido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='calculojudicial',
            name='valor_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='calculojudicial',
            name='valor_original',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.DeleteModel(
            name='HistoricalCalculoJudicial',
        ),
    ]
