# Generated by Django 5.2.1 on 2025-08-08 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0028_alter_calculojudicial_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculojudicial',
            options={'ordering': ['-data_calculo'], 'verbose_name': 'Cálculo Judicial', 'verbose_name_plural': 'Cálculos Judiciais'},
        ),
        migrations.RemoveField(
            model_name='calculojudicial',
            name='correcao_pro_rata',
        ),
        migrations.RemoveField(
            model_name='calculojudicial',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='calculojudicial',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='calculojudicial',
            name='gerar_memorial',
        ),
        migrations.RemoveField(
            model_name='calculojudicial',
            name='honorarios_percentual',
        ),
        migrations.RemoveField(
            model_name='calculojudicial',
            name='indice',
        ),
        migrations.RemoveField(
            model_name='calculojudicial',
            name='juros_data_fim',
        ),
        migrations.RemoveField(
            model_name='calculojudicial',
            name='juros_data_inicio',
        ),
        migrations.RemoveField(
            model_name='calculojudicial',
            name='juros_periodo',
        ),
        migrations.RemoveField(
            model_name='calculojudicial',
            name='juros_taxa',
        ),
        migrations.RemoveField(
            model_name='calculojudicial',
            name='juros_tipo',
        ),
        migrations.RemoveField(
            model_name='calculojudicial',
            name='memoria_calculo',
        ),
        migrations.RemoveField(
            model_name='calculojudicial',
            name='multa_percentual',
        ),
        migrations.RemoveField(
            model_name='calculojudicial',
            name='multa_sobre_juros',
        ),
        migrations.RemoveField(
            model_name='calculojudicial',
            name='valor_corrigido',
        ),
        migrations.RemoveField(
            model_name='calculojudicial',
            name='valor_final',
        ),
        migrations.AddField(
            model_name='calculojudicial',
            name='memoria_calculo_json',
            field=models.JSONField(blank=True, null=True, verbose_name='Memória de Cálculo (JSON)'),
        ),
        migrations.AddField(
            model_name='calculojudicial',
            name='valor_final_calculado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Final Calculado'),
        ),
        migrations.AlterField(
            model_name='calculojudicial',
            name='descricao',
            field=models.CharField(default='Cálculo', max_length=255, verbose_name='Descrição do Cálculo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calculojudicial',
            name='valor_original',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Original da Causa'),
        ),
        migrations.CreateModel(
            name='FaseCalculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('data_inicio', models.DateField(verbose_name='Data de Início da Fase')),
                ('data_fim', models.DateField(verbose_name='Data de Fim da Fase')),
                ('indice', models.CharField(choices=[('IPCA', 'IPCA (IBGE)'), ('INPC', 'INPC (IBGE)'), ('IGP-M', 'IGP-M (FGV/BCB)'), ('IGP-DI', 'IGP-DI (FGV/BCB)'), ('SELIC', 'Taxa Selic (BCB)'), ('TR', 'Taxa Referencial (BCB)')], max_length=50, verbose_name='Índice de Correção')),
                ('juros_taxa', models.DecimalField(decimal_places=4, default=0, max_digits=7, verbose_name='Taxa de Juros Mensal (%)')),
                ('juros_tipo', models.CharField(choices=[('SIMPLES', 'Simples'), ('COMPOSTO', 'Compostos')], default='SIMPLES', max_length=20, verbose_name='Tipo de Juros')),
                ('observacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observação da Fase')),
                ('calculo_judicial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fases', to='gestao.calculojudicial')),
            ],
            options={
                'ordering': ['calculo_judicial', 'ordem'],
            },
        ),
    ]
