# Generated by Django 5.2.1 on 2025-08-08 18:36

import gestao.encoders
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0029_alter_calculojudicial_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculojudicial',
            name='memoria_calculo_json',
            field=models.JSONField(blank=True, encoder=gestao.encoders.DecimalEncoder, null=True, verbose_name='Memória de Cálculo (JSON)'),
        ),
    ]
