# Generated by Django 5.2.1 on 2025-08-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0030_alter_calculojudicial_memoria_calculo_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculojudicial',
            name='valor_final_calculado',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=15, null=True, verbose_name='Valor Final Calculado'),
        ),
    ]
