# Generated by Django 5.2.1 on 2025-08-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0031_alter_calculojudicial_valor_final_calculado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fasecalculo',
            name='juros_taxa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Taxa de Juros Mensal (%)'),
        ),
    ]
