# Generated by Django 5.2.1 on 2025-08-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0032_alter_fasecalculo_juros_taxa'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculojudicial',
            name='campo_teste',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
