# Generated by Django 5.2.1 on 2025-08-08 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0033_calculojudicial_campo_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculojudicial',
            name='campo_teste',
        ),
    ]
